// <auto-generated />
using System;
using DATNN;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DATNN.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20251213205006_DATN")]
    partial class DATN
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DATNN.Models.ChatLieu", b =>
                {
                    b.Property<int>("MaChatLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChatLieu"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChatLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaChatLieu");

                    b.ToTable("ChatLieus");

                    b.HasData(
                        new
                        {
                            MaChatLieu = 1,
                            MoTa = "Chất liệu mềm mại, thoáng khí, phù hợp thời tiết nóng",
                            TenChatLieu = "Cotton",
                            TrangThai = 1
                        },
                        new
                        {
                            MaChatLieu = 2,
                            MoTa = "Chất liệu nhân tạo, bền, ít nhăn, dễ giặt",
                            TenChatLieu = "Polyester",
                            TrangThai = 1
                        },
                        new
                        {
                            MaChatLieu = 3,
                            MoTa = "Vải lanh mát mẻ, sang trọng, phù hợp mùa hè",
                            TenChatLieu = "Linen",
                            TrangThai = 1
                        },
                        new
                        {
                            MaChatLieu = 4,
                            MoTa = "Giữ ấm tốt, dùng cho mùa đông",
                            TenChatLieu = "Len",
                            TrangThai = 1
                        },
                        new
                        {
                            MaChatLieu = 5,
                            MoTa = "Chất liệu dày, bền, thường dùng cho quần áo cá tính",
                            TenChatLieu = "Jean (Denim)",
                            TrangThai = 1
                        },
                        new
                        {
                            MaChatLieu = 6,
                            MoTa = "Mềm mịn, bóng đẹp, thường dùng cho đồ cao cấp",
                            TenChatLieu = "Lụa",
                            TrangThai = 1
                        },
                        new
                        {
                            MaChatLieu = 7,
                            MoTa = "Co giãn tốt, thoải mái khi vận động",
                            TenChatLieu = "Vải thun",
                            TrangThai = 1
                        },
                        new
                        {
                            MaChatLieu = 8,
                            MoTa = "Giữ nhiệt tốt, thường dùng cho áo khoác, hoodie",
                            TenChatLieu = "Nỉ",
                            TrangThai = 1
                        },
                        new
                        {
                            MaChatLieu = 9,
                            MoTa = "Mỏng nhẹ, bay bổng, thường dùng cho váy nữ",
                            TenChatLieu = "Voan",
                            TrangThai = 1
                        },
                        new
                        {
                            MaChatLieu = 10,
                            MoTa = "Dày dặn, đứng form, thường dùng cho quần áo công sở",
                            TenChatLieu = "Kaki",
                            TrangThai = 1
                        },
                        new
                        {
                            MaChatLieu = 11,
                            MoTa = "Chất liệu cao cấp, bền, sang trọng",
                            TenChatLieu = "Da thật",
                            TrangThai = 1
                        },
                        new
                        {
                            MaChatLieu = 12,
                            MoTa = "Thay thế da thật, giá rẻ hơn, dễ bảo quản",
                            TenChatLieu = "Giả da",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("DATNN.Models.ChiTietGioHang", b =>
                {
                    b.Property<int>("MaChiTietGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietGioHang"));

                    b.Property<int>("MaGioHang")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPhamChiTiet")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietGioHang");

                    b.HasIndex("MaGioHang");

                    b.HasIndex("MaSanPhamChiTiet");

                    b.ToTable("ChiTietGioHangs");
                });

            modelBuilder.Entity("DATNN.Models.ChinhSach", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChinhSach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("ChinhSaches");

                    b.HasData(
                        new
                        {
                            id = 1,
                            NoiDung = "Chúng tôi cam kết bảo vệ thông tin cá nhân của người dùng. \r\n                Thông tin như tên, email, số điện thoại được thu thập nhằm mục đích xác thực tài khoản, hỗ trợ kỹ thuật và cải thiện trải nghiệm người dùng. \r\n                Dữ liệu sẽ không được chia sẻ với bên thứ ba nếu không có sự đồng ý rõ ràng từ người dùng. \r\n                Người dùng có quyền yêu cầu truy cập, chỉnh sửa hoặc xóa thông tin cá nhân bất cứ lúc nào. \r\n                Chúng tôi áp dụng các biện pháp bảo mật như mã hóa, kiểm soát truy cập và giám sát hệ thống để đảm bảo an toàn dữ liệu.",
                            TenChinhSach = "Chính sách bảo mật tài khoản"
                        },
                        new
                        {
                            id = 2,
                            NoiDung = "Khách hàng có thể yêu cầu đổi hoặc trả sản phẩm trong vòng 7 ngày kể từ ngày nhận hàng. \r\n                Điều kiện đổi trả bao gồm: sản phẩm chưa qua sử dụng, còn nguyên tem niêm phong, đầy đủ phụ kiện và hóa đơn. \r\n                Nếu sản phẩm bị lỗi kỹ thuật do nhà sản xuất, chúng tôi sẽ hỗ trợ đổi mới hoặc hoàn tiền 100%. \r\n                Quá trình xử lý đổi trả sẽ được thực hiện trong vòng 3-5 ngày làm việc kể từ khi nhận được yêu cầu. \r\n                Chúng tôi không chấp nhận đổi trả đối với các sản phẩm đã qua sử dụng hoặc bị hư hỏng do người dùng.",
                            TenChinhSach = "Chính sách đổi trả hàng"
                        },
                        new
                        {
                            id = 3,
                            NoiDung = "[...]</li></ul>",
                            TenChinhSach = "Chính sách hủy hàng"
                        });
                });

            modelBuilder.Entity("DATNN.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaDanhMuc");

                    b.ToTable("DanhMucs");

                    b.HasData(
                        new
                        {
                            MaDanhMuc = 1,
                            MoTa = "Áo thun đơn giản, dễ phối đồ",
                            TenDanhMuc = "Áo thun",
                            TrangThai = 1
                        },
                        new
                        {
                            MaDanhMuc = 2,
                            MoTa = "Áo sơ mi công sở, lịch sự",
                            TenDanhMuc = "Áo sơ mi",
                            TrangThai = 1
                        },
                        new
                        {
                            MaDanhMuc = 3,
                            MoTa = "Áo khoác giữ ấm, thời trang",
                            TenDanhMuc = "Áo khoác",
                            TrangThai = 1
                        },
                        new
                        {
                            MaDanhMuc = 4,
                            MoTa = "Quần jeans năng động, cá tính",
                            TenDanhMuc = "Quần jeans",
                            TrangThai = 1
                        },
                        new
                        {
                            MaDanhMuc = 5,
                            MoTa = "Quần tây lịch lãm, phù hợp công sở",
                            TenDanhMuc = "Quần tây",
                            TrangThai = 1
                        },
                        new
                        {
                            MaDanhMuc = 6,
                            MoTa = "Váy nữ tính, đa dạng kiểu dáng",
                            TenDanhMuc = "Váy đầm",
                            TrangThai = 1
                        },
                        new
                        {
                            MaDanhMuc = 7,
                            MoTa = "Trang phục thể thao thoải mái",
                            TenDanhMuc = "Đồ thể thao",
                            TrangThai = 1
                        },
                        new
                        {
                            MaDanhMuc = 8,
                            MoTa = "Đồ ngủ mềm mại, dễ chịu",
                            TenDanhMuc = "Đồ ngủ",
                            TrangThai = 1
                        },
                        new
                        {
                            MaDanhMuc = 9,
                            MoTa = "Đồ lót nam nữ các loại",
                            TenDanhMuc = "Đồ lót",
                            TrangThai = 1
                        },
                        new
                        {
                            MaDanhMuc = 10,
                            MoTa = "Áo hoodie trẻ trung, cá tính",
                            TenDanhMuc = "Áo hoodie",
                            TrangThai = 1
                        },
                        new
                        {
                            MaDanhMuc = 11,
                            MoTa = "Áo len giữ ấm mùa đông",
                            TenDanhMuc = "Áo len",
                            TrangThai = 1
                        },
                        new
                        {
                            MaDanhMuc = 12,
                            MoTa = "Quần short mát mẻ, năng động",
                            TenDanhMuc = "Quần short",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("DATNN.Models.DiaChiCuaHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChiTietDiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Phuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThanhPho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaChiCuaHangs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChiTietDiaChi = "Tổ 6",
                            Latitude = 21.182207399999999,
                            Longitude = 105.72168360000001,
                            Phuong = "Thị trấn Quang Minh",
                            Quan = "Huyện Mê Linh",
                            ThanhPho = "Thành phố Hà Nội"
                        });
                });

            modelBuilder.Entity("DATNN.Models.DiaChiNguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChiTietDiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("Phuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThanhPho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("DiaChiNguoiDungs");
                });

            modelBuilder.Entity("DATNN.Models.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonHang"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenNguoiNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LichSuTrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDoHuy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaGiamGiaID")
                        .HasColumnType("int");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaKhuyenMai")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<decimal?>("PhiVanChuyen")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SoTienDuocGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TienMatDaNhan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThaiDonHang")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiThanhToan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VnpPayDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VnpTransactionNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VnpTxnRef")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDonHang");

                    b.HasIndex("MaGiamGiaID");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaKhuyenMai");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("DATNN.Models.DonHangChiTiet", b =>
                {
                    b.Property<int>("MaDonHangChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonHangChiTiet"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh_Luu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPhamChiTiet")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenMau_Luu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham_Luu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSize_Luu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDonHangChiTiet");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaSanPhamChiTiet");

                    b.ToTable("DonHangChiTiets");
                });

            modelBuilder.Entity("DATNN.Models.GioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGioHang"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaGioHang");

                    b.HasIndex("MaNguoiDung")
                        .IsUnique();

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("DATNN.Models.KhuyenMai", b =>
                {
                    b.Property<int>("MaKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhuyenMai"));

                    b.Property<string>("DanhSachSanPhamApDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("GiaTriGiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KenhApDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiGiamGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaKhuyenMai");

                    b.ToTable("KhuyenMais");
                });

            modelBuilder.Entity("DATNN.Models.MaGiamGia", b =>
                {
                    b.Property<int>("MaGiamGiaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiamGiaID"));

                    b.Property<int>("DaSuDung")
                        .HasColumnType("int");

                    b.Property<string>("DanhSachSanPhamApDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DieuKienDonHangToiThieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaTriGiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KenhApDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiApDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiGiamGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenChuongTrinh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("TongLuotSuDungToiDa")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaGiamGiaID");

                    b.ToTable("MaGiamGias");
                });

            modelBuilder.Entity("DATNN.Models.MauSac", b =>
                {
                    b.Property<int>("MaMauSac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMauSac"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaMauSac");

                    b.ToTable("MauSacs");

                    b.HasData(
                        new
                        {
                            MaMauSac = 1,
                            MoTa = "#FF0000",
                            TenMau = "Đỏ",
                            TrangThai = 1
                        },
                        new
                        {
                            MaMauSac = 2,
                            MoTa = "#0000FF",
                            TenMau = "Xanh dương",
                            TrangThai = 1
                        },
                        new
                        {
                            MaMauSac = 3,
                            MoTa = "#FFFF00",
                            TenMau = "Vàng",
                            TrangThai = 1
                        },
                        new
                        {
                            MaMauSac = 4,
                            MoTa = "#00FF00",
                            TenMau = "Xanh lá cây",
                            TrangThai = 1
                        },
                        new
                        {
                            MaMauSac = 5,
                            MoTa = "#FFA500",
                            TenMau = "Cam",
                            TrangThai = 1
                        },
                        new
                        {
                            MaMauSac = 6,
                            MoTa = "#800080",
                            TenMau = "Tím",
                            TrangThai = 1
                        },
                        new
                        {
                            MaMauSac = 7,
                            MoTa = "#FFC0CB",
                            TenMau = "Hồng",
                            TrangThai = 1
                        },
                        new
                        {
                            MaMauSac = 8,
                            MoTa = "#A52A2A",
                            TenMau = "Nâu",
                            TrangThai = 1
                        },
                        new
                        {
                            MaMauSac = 9,
                            MoTa = "#000000",
                            TenMau = "Đen",
                            TrangThai = 1
                        },
                        new
                        {
                            MaMauSac = 10,
                            MoTa = "#FFFFFF",
                            TenMau = "Trắng",
                            TrangThai = 1
                        },
                        new
                        {
                            MaMauSac = 11,
                            MoTa = "#808080",
                            TenMau = "Xám",
                            TrangThai = 1
                        },
                        new
                        {
                            MaMauSac = 12,
                            MoTa = "#00CED1",
                            TenMau = "Xanh ngọc",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("DATNN.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaQuyen")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("TokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("MaQuyen");

                    b.HasIndex(new[] { "Email" }, "IX_NguoiDung_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "TenDangNhap" }, "IX_NguoiDung_TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDungs");

                    b.HasData(
                        new
                        {
                            MaNguoiDung = 1,
                            Email = "admin@example.com",
                            GioiTinh = "Nam",
                            HoTen = "Quản trị viên",
                            MaQuyen = 1,
                            MatKhau = "AQAAAAIAAYagAAAAENa6tfOCNlmIuKKfP5aBy3xmrAvlx93io3bqEuNCmdQgG1u+vvHR0Zc0Q3i9OeAHlg==",
                            NgaySinh = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2025, 8, 11, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000001",
                            TenDangNhap = "admin",
                            TrangThai = 1
                        },
                        new
                        {
                            MaNguoiDung = 2,
                            Email = "nhanvien@example.com",
                            GioiTinh = "Nam",
                            HoTen = "Nguyễn Văn Nhân",
                            MaQuyen = 2,
                            MatKhau = "AQAAAAIAAYagAAAAENa6tfOCNlmIuKKfP5aBy3xmrAvlx93io3bqEuNCmdQgG1u+vvHR0Zc0Q3i9OeAHlg==",
                            NgaySinh = new DateTime(1995, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2025, 8, 11, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000002",
                            TenDangNhap = "nhanvien",
                            TrangThai = 1
                        },
                        new
                        {
                            MaNguoiDung = 3,
                            Email = "khach@example.com",
                            GioiTinh = "Nữ",
                            HoTen = "Trần Thị Khách",
                            MaQuyen = 3,
                            MatKhau = "AQAAAAIAAYagAAAAENa6tfOCNlmIuKKfP5aBy3xmrAvlx93io3bqEuNCmdQgG1u+vvHR0Zc0Q3i9OeAHlg==",
                            NgaySinh = new DateTime(2000, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2025, 8, 11, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000003",
                            TenDangNhap = "khachhang",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("DATNN.Models.PhieuChi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("LoaiChiPhi")
                        .HasColumnType("int");

                    b.Property<int?>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("MaYeuCauDoiTra")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaYeuCauDoiTra");

                    b.ToTable("PhieuChis");
                });

            modelBuilder.Entity("DATNN.Models.Quyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Quyens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaVaiTro = "ADMIN",
                            Ten = "Quản trị viên",
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 2,
                            MaVaiTro = "NHANVIEN",
                            Ten = "Nhân viên",
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 3,
                            MaVaiTro = "KHACHHANG",
                            Ten = "Khách hàng",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("DATNN.Models.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSanPham"));

                    b.Property<string>("AnhSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaChatLieu")
                        .HasColumnType("int");

                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<int>("MaXuatXu")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaSanPham");

                    b.HasIndex("MaChatLieu");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("MaXuatXu");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            MaSanPham = 1,
                            AnhSanPham = "34239af7-9bc2-4259-b9aa-5c4d6d982383.webp",
                            MaChatLieu = 1,
                            MaDanhMuc = 1,
                            MaXuatXu = 1,
                            MoTa = "Áo thun cotton thoáng mát, phù hợp mùa hè",
                            TenSanPham = "Áo thun nam basic",
                            ThoiGianTao = new DateTime(2025, 8, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = 1
                        },
                        new
                        {
                            MaSanPham = 2,
                            AnhSanPham = "e3494b8b-9ee4-43a2-8b97-51ac8b5d269d.webp",
                            MaChatLieu = 2,
                            MaDanhMuc = 2,
                            MaXuatXu = 2,
                            MoTa = "Áo sơ mi lịch sự, phù hợp môi trường văn phòng",
                            TenSanPham = "Áo sơ mi trắng công sở",
                            ThoiGianTao = new DateTime(2025, 8, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = 1
                        },
                        new
                        {
                            MaSanPham = 3,
                            AnhSanPham = "db61a7eb-6e34-4ca1-8c32-da30bf68edfd.webp",
                            MaChatLieu = 3,
                            MaDanhMuc = 3,
                            MaXuatXu = 3,
                            MoTa = "Áo hoodie nỉ ấm, phong cách trẻ trung",
                            TenSanPham = "Áo khoác hoodie unisex",
                            ThoiGianTao = new DateTime(2025, 8, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = 1
                        },
                        new
                        {
                            MaSanPham = 4,
                            AnhSanPham = "5a60f6f7-e20c-44eb-9cb5-88fdb944f13c.webp",
                            MaChatLieu = 4,
                            MaDanhMuc = 4,
                            MaXuatXu = 4,
                            MoTa = "Quần jeans cá tính, phong cách đường phố",
                            TenSanPham = "Quần jeans rách gối",
                            ThoiGianTao = new DateTime(2025, 8, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = 1
                        },
                        new
                        {
                            MaSanPham = 5,
                            AnhSanPham = "2693f29b-9566-4972-ae7e-9dc3bbb9117a.webp",
                            MaChatLieu = 5,
                            MaDanhMuc = 5,
                            MaXuatXu = 5,
                            MoTa = "Váy nữ tính, chất liệu voan nhẹ nhàng",
                            TenSanPham = "Váy voan xếp ly",
                            ThoiGianTao = new DateTime(2025, 8, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = 1
                        },
                        new
                        {
                            MaSanPham = 6,
                            AnhSanPham = "6f339380-7919-4e1d-87b7-76bd54febf5b.webp",
                            MaChatLieu = 6,
                            MaDanhMuc = 6,
                            MaXuatXu = 6,
                            MoTa = "Áo len giữ ấm, phù hợp mùa đông",
                            TenSanPham = "Áo len cổ lọ",
                            ThoiGianTao = new DateTime(2025, 8, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("DATNN.Models.SanPhamChiTiet", b =>
                {
                    b.Property<int>("MaSanPhamChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSanPhamChiTiet"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaMauSac")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<int>("MaSize")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaSanPhamChiTiet");

                    b.HasIndex("MaMauSac");

                    b.HasIndex("MaSanPham");

                    b.HasIndex("MaSize");

                    b.ToTable("SanPhamChiTiets");

                    b.HasData(
                        new
                        {
                            MaSanPhamChiTiet = 1,
                            GhiChu = "Màu đỏ - Size S",
                            GiaBan = 199000.00m,
                            HinhAnh = "e35219ca-1040-42ab-ad5a-292be7750b18.webp",
                            MaMauSac = 1,
                            MaSanPham = 1,
                            MaSize = 1,
                            SoLuong = 50,
                            TrangThai = 1
                        },
                        new
                        {
                            MaSanPhamChiTiet = 2,
                            GhiChu = "Màu xanh dương - Size M",
                            GiaBan = 199000.00m,
                            HinhAnh = "4a5e7e4b-27f6-437c-8874-5e03278df64f.webp",
                            MaMauSac = 2,
                            MaSanPham = 1,
                            MaSize = 2,
                            SoLuong = 40,
                            TrangThai = 1
                        },
                        new
                        {
                            MaSanPhamChiTiet = 3,
                            GhiChu = "Màu vàng - Size L",
                            GiaBan = 199000.00m,
                            HinhAnh = "a1695aa7-705e-48d0-b28b-464aa5c570f3.webp",
                            MaMauSac = 3,
                            MaSanPham = 1,
                            MaSize = 3,
                            SoLuong = 30,
                            TrangThai = 1
                        },
                        new
                        {
                            MaSanPhamChiTiet = 4,
                            GhiChu = "Size S",
                            GiaBan = 249000.00m,
                            HinhAnh = "95918186-de09-413f-9518-77100c34f79d.webp",
                            MaMauSac = 10,
                            MaSanPham = 2,
                            MaSize = 1,
                            SoLuong = 30,
                            TrangThai = 1
                        },
                        new
                        {
                            MaSanPhamChiTiet = 5,
                            GhiChu = "Size M",
                            GiaBan = 249000.00m,
                            HinhAnh = "05ea2664-5ed0-4272-aaa2-66de76935ed3.webp",
                            MaMauSac = 10,
                            MaSanPham = 2,
                            MaSize = 2,
                            SoLuong = 45,
                            TrangThai = 1
                        },
                        new
                        {
                            MaSanPhamChiTiet = 6,
                            GhiChu = "Size L",
                            GiaBan = 249000.00m,
                            HinhAnh = "1a97e244-2280-470c-9f42-c6cca8d17f29.webp",
                            MaMauSac = 6,
                            MaSanPham = 2,
                            MaSize = 3,
                            SoLuong = 35,
                            TrangThai = 1
                        },
                        new
                        {
                            MaSanPhamChiTiet = 7,
                            GhiChu = "Màu hồng - Size M",
                            GiaBan = 299000.00m,
                            HinhAnh = "7c236dee-12f7-43fd-bc06-7330c651ead1.webp",
                            MaMauSac = 7,
                            MaSanPham = 3,
                            MaSize = 2,
                            SoLuong = 70,
                            TrangThai = 1
                        },
                        new
                        {
                            MaSanPhamChiTiet = 8,
                            GhiChu = "Màu nâu - Size L",
                            GiaBan = 299000.00m,
                            HinhAnh = "98aad352-f160-443e-8bc7-df0bb1254223.webp",
                            MaMauSac = 8,
                            MaSanPham = 3,
                            MaSize = 3,
                            SoLuong = 50,
                            TrangThai = 1
                        },
                        new
                        {
                            MaSanPhamChiTiet = 9,
                            GhiChu = "Màu đen - Size XL",
                            GiaBan = 299000.00m,
                            HinhAnh = "28a18cbb-b318-4234-b96c-d51d0eb8dba6.webp",
                            MaMauSac = 9,
                            MaSanPham = 3,
                            MaSize = 4,
                            SoLuong = 40,
                            TrangThai = 1
                        },
                        new
                        {
                            MaSanPhamChiTiet = 10,
                            GhiChu = "Màu xám - Size S",
                            GiaBan = 279000.00m,
                            HinhAnh = "d7e66c3a-a1e0-48f5-b37c-9384babe5f22.webp",
                            MaMauSac = 11,
                            MaSanPham = 4,
                            MaSize = 1,
                            SoLuong = 55,
                            TrangThai = 1
                        },
                        new
                        {
                            MaSanPhamChiTiet = 11,
                            GhiChu = "Màu xám - Size M",
                            GiaBan = 279000.00m,
                            HinhAnh = "56d9df18-36fc-4c2c-b6f9-7a77275dad64.webp",
                            MaMauSac = 11,
                            MaSanPham = 4,
                            MaSize = 2,
                            SoLuong = 45,
                            TrangThai = 1
                        },
                        new
                        {
                            MaSanPhamChiTiet = 12,
                            GhiChu = "Màu xám - Size L",
                            GiaBan = 279000.00m,
                            HinhAnh = "3b010930-6373-4c3f-afbe-f2c08374534d.webp",
                            MaMauSac = 11,
                            MaSanPham = 4,
                            MaSize = 3,
                            SoLuong = 35,
                            TrangThai = 1
                        },
                        new
                        {
                            MaSanPhamChiTiet = 13,
                            GhiChu = "Màu đỏ - Size M",
                            GiaBan = 319000.00m,
                            HinhAnh = "ffa63165-c6be-4c9e-98b6-febfbe1fae71.webp",
                            MaMauSac = 1,
                            MaSanPham = 5,
                            MaSize = 3,
                            SoLuong = 40,
                            TrangThai = 1
                        },
                        new
                        {
                            MaSanPhamChiTiet = 14,
                            GhiChu = "Màu xanh dương - Size L",
                            GiaBan = 319000.00m,
                            HinhAnh = "04131487-a5f2-4750-8fad-faaf1d173617.webp",
                            MaMauSac = 2,
                            MaSanPham = 5,
                            MaSize = 3,
                            SoLuong = 30,
                            TrangThai = 1
                        },
                        new
                        {
                            MaSanPhamChiTiet = 15,
                            GhiChu = "Màu vàng - Size XL",
                            GiaBan = 319000.00m,
                            HinhAnh = "c6c7731d-bfea-4056-b54d-1353eb200919.webp",
                            MaMauSac = 3,
                            MaSanPham = 5,
                            MaSize = 4,
                            SoLuong = 20,
                            TrangThai = 1
                        },
                        new
                        {
                            MaSanPhamChiTiet = 16,
                            GhiChu = "Màu xanh lá - Size M",
                            GiaBan = 259000.00m,
                            HinhAnh = "869f6d1d-17ee-4745-b1c8-b06a6d773c7a.webp",
                            MaMauSac = 4,
                            MaSanPham = 6,
                            MaSize = 2,
                            SoLuong = 50,
                            TrangThai = 1
                        },
                        new
                        {
                            MaSanPhamChiTiet = 17,
                            GhiChu = "Màu cam - Size L",
                            GiaBan = 259000.00m,
                            HinhAnh = "6bc27c82-af10-4a6d-a378-bb27569e3f9f.webp",
                            MaMauSac = 4,
                            MaSanPham = 6,
                            MaSize = 3,
                            SoLuong = 40,
                            TrangThai = 1
                        },
                        new
                        {
                            MaSanPhamChiTiet = 18,
                            GhiChu = "Màu tím - Size XL",
                            GiaBan = 259000.00m,
                            HinhAnh = "550f7a41-1020-4847-85bc-1bc9454192e0.webp",
                            MaMauSac = 6,
                            MaSanPham = 6,
                            MaSize = 4,
                            SoLuong = 30,
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("DATNN.Models.Size", b =>
                {
                    b.Property<int>("MaSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSize"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaSize");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            MaSize = 1,
                            MoTa = "Extra Small – Rất nhỏ",
                            TenSize = "XS",
                            TrangThai = 1
                        },
                        new
                        {
                            MaSize = 2,
                            MoTa = "Small – Nhỏ",
                            TenSize = "S",
                            TrangThai = 1
                        },
                        new
                        {
                            MaSize = 3,
                            MoTa = "Medium – Vừa",
                            TenSize = "M",
                            TrangThai = 1
                        },
                        new
                        {
                            MaSize = 4,
                            MoTa = "Large – Lớn",
                            TenSize = "L",
                            TrangThai = 1
                        },
                        new
                        {
                            MaSize = 5,
                            MoTa = "Extra Large – Rất lớn",
                            TenSize = "XL",
                            TrangThai = 1
                        },
                        new
                        {
                            MaSize = 6,
                            MoTa = "Double Extra Large – Siêu lớn",
                            TenSize = "XXL",
                            TrangThai = 1
                        },
                        new
                        {
                            MaSize = 7,
                            MoTa = "Triple Extra Large – Cực lớn",
                            TenSize = "3XL",
                            TrangThai = 1
                        },
                        new
                        {
                            MaSize = 8,
                            MoTa = "Kích thước tự do – phù hợp nhiều vóc dáng",
                            TenSize = "Free Size",
                            TrangThai = 1
                        },
                        new
                        {
                            MaSize = 9,
                            MoTa = "Size quần 28 – nhỏ",
                            TenSize = "28",
                            TrangThai = 1
                        },
                        new
                        {
                            MaSize = 10,
                            MoTa = "Size quần 30 – trung bình",
                            TenSize = "30",
                            TrangThai = 1
                        },
                        new
                        {
                            MaSize = 11,
                            MoTa = "Size quần 32 – lớn",
                            TenSize = "32",
                            TrangThai = 1
                        },
                        new
                        {
                            MaSize = 12,
                            MoTa = "Size quần 34 – rất lớn",
                            TenSize = "34",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("DATNN.Models.SystemSetting", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SettingKey");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("DATNN.Models.ThongTinCuaHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("DongCua")
                        .HasColumnType("time");

                    b.Property<string>("Gmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeOnly>("MoCua")
                        .HasColumnType("time");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenCuaHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ThongTinCuaHangs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DongCua = new TimeOnly(23, 0, 0),
                            Gmail = "hienngoc@example.com",
                            MoCua = new TimeOnly(6, 0, 0),
                            SoDienThoai = "0388118966",
                            TenCuaHang = "hiện ngọc"
                        });
                });

            modelBuilder.Entity("DATNN.Models.ThongTinGiaoHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BanKinhGiaoHang")
                        .HasColumnType("float");

                    b.Property<double>("BanKinhfree")
                        .HasColumnType("float");

                    b.Property<decimal>("DonHangToiThieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PhiGiaoHang")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ThongTinGiaoHangs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BanKinhGiaoHang = 15.0,
                            BanKinhfree = 3.0,
                            DonHangToiThieu = 50000m,
                            PhiGiaoHang = 5000m
                        });
                });

            modelBuilder.Entity("DATNN.Models.XuatXu", b =>
                {
                    b.Property<int>("MaXuatXu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaXuatXu"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenXuatXu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaXuatXu");

                    b.ToTable("XuatXus");

                    b.HasData(
                        new
                        {
                            MaXuatXu = 1,
                            MoTa = "Sản xuất trong nước, chất lượng ổn định",
                            TenXuatXu = "Việt Nam",
                            TrangThai = 1
                        },
                        new
                        {
                            MaXuatXu = 2,
                            MoTa = "Giá thành cạnh tranh, sản xuất quy mô lớn",
                            TenXuatXu = "Trung Quốc",
                            TrangThai = 1
                        },
                        new
                        {
                            MaXuatXu = 3,
                            MoTa = "Thiết kế hiện đại, thời trang cao cấp",
                            TenXuatXu = "Hàn Quốc",
                            TrangThai = 1
                        },
                        new
                        {
                            MaXuatXu = 4,
                            MoTa = "Chất lượng cao, độ bền tốt",
                            TenXuatXu = "Nhật Bản",
                            TrangThai = 1
                        },
                        new
                        {
                            MaXuatXu = 5,
                            MoTa = "Mẫu mã đẹp, giá hợp lý",
                            TenXuatXu = "Thái Lan",
                            TrangThai = 1
                        },
                        new
                        {
                            MaXuatXu = 6,
                            MoTa = "Tiêu chuẩn quốc tế, thương hiệu uy tín",
                            TenXuatXu = "Mỹ",
                            TrangThai = 1
                        },
                        new
                        {
                            MaXuatXu = 7,
                            MoTa = "Phong cách sang trọng, thời trang cao cấp",
                            TenXuatXu = "Pháp",
                            TrangThai = 1
                        },
                        new
                        {
                            MaXuatXu = 8,
                            MoTa = "Thời trang đẳng cấp, thiết kế tinh tế",
                            TenXuatXu = "Ý",
                            TrangThai = 1
                        },
                        new
                        {
                            MaXuatXu = 9,
                            MoTa = "Kỹ thuật chính xác, độ bền cao",
                            TenXuatXu = "Đức",
                            TrangThai = 1
                        },
                        new
                        {
                            MaXuatXu = 10,
                            MoTa = "Phong cách cổ điển, chất lượng tốt",
                            TenXuatXu = "Anh",
                            TrangThai = 1
                        },
                        new
                        {
                            MaXuatXu = 11,
                            MoTa = "Nguyên liệu tự nhiên, giá tốt",
                            TenXuatXu = "Ấn Độ",
                            TrangThai = 1
                        },
                        new
                        {
                            MaXuatXu = 12,
                            MoTa = "Sản xuất khu vực Đông Nam Á",
                            TenXuatXu = "Indonesia",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("DATNN.Models.YeuCauDoiTra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BenChiuPhiShip")
                        .HasColumnType("int");

                    b.Property<string>("ChiNhanh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("ChiPhiShip")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("GhiChuAdmin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GiaSanPhamMoi_Luu")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("HinhAnhBangChung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnhMoi_Luu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HinhThucHoanTien")
                        .HasColumnType("int");

                    b.Property<int>("LoaiYeuCau")
                        .HasColumnType("int");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaDonHangChiTiet")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("MaSanPhamChiTietMoi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongYeuCau")
                        .HasColumnType("int");

                    b.Property<string>("SoTaiKhoan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenChuTaiKhoan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenMauMoi_Luu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenNganHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenSanPhamMoi_Luu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenSizeMoi_Luu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TienChenhLech")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("TongTienThanhToan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaDonHangChiTiet");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("YeuCauDoiTras");
                });

            modelBuilder.Entity("DATNN.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("DATNN.Models.GioHang", "GioHang")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaGioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATNN.Models.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GioHang");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("DATNN.Models.DiaChiNguoiDung", b =>
                {
                    b.HasOne("DATNN.Models.NguoiDung", "NguoiDung")
                        .WithMany("DiaChiNguoiDungs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DATNN.Models.DonHang", b =>
                {
                    b.HasOne("DATNN.Models.MaGiamGia", "MaGiamGia")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaGiamGiaID");

                    b.HasOne("DATNN.Models.NguoiDung", "KhachHang")
                        .WithMany("DonHangsKhachHang")
                        .HasForeignKey("MaKhachHang");

                    b.HasOne("DATNN.Models.KhuyenMai", "KhuyenMai")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKhuyenMai");

                    b.HasOne("DATNN.Models.NguoiDung", "NguoiDung")
                        .WithMany("DonHangsNhanVien")
                        .HasForeignKey("MaNguoiDung");

                    b.Navigation("KhachHang");

                    b.Navigation("KhuyenMai");

                    b.Navigation("MaGiamGia");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DATNN.Models.DonHangChiTiet", b =>
                {
                    b.HasOne("DATNN.Models.DonHang", "DonHang")
                        .WithMany("DonHangChiTiets")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATNN.Models.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("DonHangChiTiets")
                        .HasForeignKey("MaSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("DATNN.Models.GioHang", b =>
                {
                    b.HasOne("DATNN.Models.NguoiDung", "NguoiDung")
                        .WithOne("GioHang")
                        .HasForeignKey("DATNN.Models.GioHang", "MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DATNN.Models.NguoiDung", b =>
                {
                    b.HasOne("DATNN.Models.Quyen", "Quyen")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quyen");
                });

            modelBuilder.Entity("DATNN.Models.PhieuChi", b =>
                {
                    b.HasOne("DATNN.Models.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("MaDonHang");

                    b.HasOne("DATNN.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung");

                    b.HasOne("DATNN.Models.YeuCauDoiTra", "YeuCauDoiTra")
                        .WithMany()
                        .HasForeignKey("MaYeuCauDoiTra");

                    b.Navigation("DonHang");

                    b.Navigation("NguoiDung");

                    b.Navigation("YeuCauDoiTra");
                });

            modelBuilder.Entity("DATNN.Models.SanPham", b =>
                {
                    b.HasOne("DATNN.Models.ChatLieu", "ChatLieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaChatLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATNN.Models.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATNN.Models.XuatXu", "XuatXu")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaXuatXu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatLieu");

                    b.Navigation("DanhMuc");

                    b.Navigation("XuatXu");
                });

            modelBuilder.Entity("DATNN.Models.SanPhamChiTiet", b =>
                {
                    b.HasOne("DATNN.Models.MauSac", "MauSac")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("MaMauSac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATNN.Models.SanPham", "SanPham")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATNN.Models.Size", "Size")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("MaSize")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MauSac");

                    b.Navigation("SanPham");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("DATNN.Models.YeuCauDoiTra", b =>
                {
                    b.HasOne("DATNN.Models.DonHangChiTiet", "DonHangChiTiet")
                        .WithMany()
                        .HasForeignKey("MaDonHangChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATNN.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHangChiTiet");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DATNN.Models.ChatLieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("DATNN.Models.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("DATNN.Models.DonHang", b =>
                {
                    b.Navigation("DonHangChiTiets");
                });

            modelBuilder.Entity("DATNN.Models.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("DATNN.Models.KhuyenMai", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("DATNN.Models.MaGiamGia", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("DATNN.Models.MauSac", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("DATNN.Models.NguoiDung", b =>
                {
                    b.Navigation("DiaChiNguoiDungs");

                    b.Navigation("DonHangsKhachHang");

                    b.Navigation("DonHangsNhanVien");

                    b.Navigation("GioHang")
                        .IsRequired();
                });

            modelBuilder.Entity("DATNN.Models.Quyen", b =>
                {
                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("DATNN.Models.SanPham", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("DATNN.Models.SanPhamChiTiet", b =>
                {
                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("DonHangChiTiets");
                });

            modelBuilder.Entity("DATNN.Models.Size", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("DATNN.Models.XuatXu", b =>
                {
                    b.Navigation("SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
